# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 14:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mastery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_type', models.PositiveIntegerField(choices=[(1, 'Domain'), (2, 'School'), (3, 'Bloodline')])),
                ('name', models.CharField(max_length=128)),
                ('specializes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spells.Mastery')),
            ],
        ),
        migrations.CreateModel(
            name='MasteryLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('mastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.Mastery')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('permitted_masteries_types', models.CharField(max_length=16, validators=(django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.'),))),
                ('masteries', models.ManyToManyField(to='spells.Mastery')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('masteries', models.ManyToManyField(through='spells.MasteryLevel', to='spells.Mastery')),
            ],
        ),
        migrations.CreateModel(
            name='SpellsPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('num_of_spells', models.PositiveIntegerField()),
                ('player_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.PlayerClass')),
            ],
        ),
        migrations.AddField(
            model_name='masterylevel',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.Spell'),
        ),
        migrations.AlterUniqueTogether(
            name='spellsperday',
            unique_together=set([('level', 'num_of_spells', 'player_class')]),
        ),
        migrations.AlterUniqueTogether(
            name='masterylevel',
            unique_together=set([('level', 'spell', 'mastery')]),
        ),
        migrations.AlterUniqueTogether(
            name='mastery',
            unique_together=set([('spell_type', 'name')]),
        ),
    ]
