# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerclass',
            name='masteries',
        ),
        migrations.AlterField(
            model_name='mastery',
            name='mastery_type',
            field=models.PositiveIntegerField(choices=[(0, 'School'), (1, 'Domain'), (2, 'Bloodline'), (3, 'Mystery'), (4, 'Patron')], default=0),
        ),
        migrations.AlterField(
            model_name='masterylevel',
            name='level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
