# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 07:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_auto_20170718_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerclass',
            name='permitted_mastery_types',
            field=models.CharField(default='0', max_length=16, validators=(django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.'),)),
        ),
    ]
