# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spelltables', '0003_auto_20170811_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
